Repository CruGlobal/mobile-content-api, pull requests merged in 2021-05, with the labels that each got.

#671 GT-1173 add documentation around the default colors a training tip should use for content
  public/xmlns/training.xsd
Labels: Content Spec

#672 only allow the followup namespace for event ids
  public/xmlns/content.xsd
  schema_tests/tract/valid/tests/buttons.xml
  schema_tests/tract/valid/tests/call-to-action.xml
Labels: Content Spec, On Staging

#688 Use more modern datadog config
  config/initializers/ddtrace.rb
Labels: On Staging
